import QueryProviders from '@/lib/queryProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Raleway, Sofia_Sans } from 'next/font/google'
import { Toaster } from 'sonner'
import AuthProvider from '@/lib/authProvider'
import LoadingBar from '@/components/LoadingBar'

export const metadata: Metadata = {
  title: 'Doc_Time / Doctor Appointment Online',
  description: 'Generated by create next app',
}

const ral = Raleway({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-raleway"
})
const sofia = Sofia_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-sofia"
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${ral.variable} ${sofia.variable} overflow-x-hidden`}>
        <Toaster richColors />
        <LoadingBar />
        <AuthProvider>
          <QueryProviders>
            {children}
          </QueryProviders>
        </AuthProvider>
      </body>
    </html>
  )
}
